# Generated by Django 4.1 on 2023-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spechtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
